[general]
resolution = 1024
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 4096
bucket_reso_steps = 64

[[datasets]]
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/1_twitslop/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/4_r34/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/3_da_1/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/1_source_pixiv/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/1_e6slop/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/1_e6ai_hot/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/1_e6/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/1_db/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/1_curated/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/1_aibooru_ranked/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/1_aibooru/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/velvet-aesthetic/1_curated/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0.1
    caption_tag_dropout_rate  = 0.4
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/full-data/ai-datapatreon/"
    num_repeats               = 1
    shuffle_caption           = true
    [[datasets.subsets]]
    caption_dropout_rate      = 0
    caption_tag_dropout_rate  = 0
    caption_extension         = ".txt"
    image_dir                 = "/home/bluvoll/Escritorio/colors/black/"
    num_repeats               = 5
    shuffle_caption           = true

    